---
- name: 'Add icinga ppas'
  apt_repository:
    repo=ppa:formorer/icinga
    state=present

- name: 'Install icinga'
  apt:
    name='{{ item }}'
    state=present
  with_items:
    - icinga2
    - icingaweb2
    - icinga2-ido-mysql

